### ISSUE TITLE
Dimension of Equation 2

### ISSUE THREAD

**Issue by xiewende** [HeimingX/semi_seg_proto#3]
Nice Works! 
Can you give a more detailed about the dimensional of equation 2 with prototype number of per-class = 4 ?

**Comment by HeimingX** [comment]
Hi, thanks for your interest in our work. The dimension is 512 for prototypes and the immediate feature representations. Furthermore, in order to enable the GPU memory to accommodate such dense similarity calculation, we do a grid sampling on the immediate feature representation and the sampling granularity is set to 32 by default, i.e., 32*32 feature representations are sampled for prototype-based prediction.
